# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_bytes_extra.proto
# Protobuf Python Version: 5.28.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '-rc2',
    'msg_bytes_extra.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15msg_bytes_extra.proto\"\x84\x01\n\nBytesExtra\x12\x1b\n\x02\x66\x31\x18\x01 \x03(\x0b\x32\x0f.BytesExtra.KV1\x12\x1b\n\x02\x66\x33\x18\x03 \x03(\x0b\x32\x0f.BytesExtra.KV3\x1a\x1d\n\x03KV1\x12\n\n\x02s1\x18\x01 \x01(\x05\x12\n\n\x02s2\x18\x02 \x01(\x05\x1a\x1d\n\x03KV3\x12\n\n\x02s1\x18\x01 \x01(\x05\x12\n\n\x02s2\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_bytes_extra_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BYTESEXTRA']._serialized_start=26
  _globals['_BYTESEXTRA']._serialized_end=158
  _globals['_BYTESEXTRA_KV1']._serialized_start=98
  _globals['_BYTESEXTRA_KV1']._serialized_end=127
  _globals['_BYTESEXTRA_KV3']._serialized_start=129
  _globals['_BYTESEXTRA_KV3']._serialized_end=158
# @@protoc_insertion_point(module_scope)
