# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cr_v4_ext_buffer.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'cr_v4_ext_buffer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63r_v4_ext_buffer.proto\"@\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x66lag\x18\x03 \x01(\x05\x12\x10\n\x08group_id\x18\x04 \x01(\t\"V\n\x08\x43hatRoom\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\x03\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\x03\x12\x12\n\nextra_data\x18\x05 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cr_v4_ext_buffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=26
  _globals['_USER']._serialized_end=90
  _globals['_CHATROOM']._serialized_start=92
  _globals['_CHATROOM']._serialized_end=178
# @@protoc_insertion_point(module_scope)
